numbers=[5,2,1,7,4]
numbers.append(20)
print(numbers)
numbers.insert(0, 10)
print(numbers)
numbers.remove(2)
print(numbers)
print(numbers.count(5))
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
number2 = numbers.copy()
print(number2)
numbers.pop()
print(numbers)
print(numbers.index(50))
print(50 in numbers)
